GenresReplace = {
    '69 (Position)': ['69', '69 position', 'sixty-nine'],
    'Airplane' : ['airplane / airport / flight Attendant','airplaine','airport','flight attendant'],
    'All Natural': ['natural'],
    'Amateur': ['amateur pre auditions', 'amatuer'],
    'Anal Fingering': ['ass fingering'],
    'Anal' : ['ass Fuck','ass fucking'],
    'Asian': ['asian amateur'],
    'Ass Eating': ['ass licking'],
    'Ass to Mouth': ['atm'],
    'Ass': ['booty', 'butt'],
    'Athletic Body': ['athlete', 'athletic', 'fit', 'fit body','athletic woman'],
    'Ball Gag': ['ballgagged'],
    'Ball Licking': ['ball lick', 'ball sucking'],
    'Bareback': ['no condom'],
    'Barely Legal': ['barely-legal'],
    'BBW': ['big beautiful women'],
    'Behind the Scenes': ['behind the scene', 'bts', 'behind-the-scenes', 'backstage'],
    'Big Butt': ['bib booty', 'big ass', 'big booty', 'big butts', 'fat ass', 'girl big ass'],
    'Big Dick': ['2 big cocks', 'big cock', 'big cocks', 'big dicks'],
    'Big Natural Tits': ['big naturals'],
    'Big Nipples': ['big areolas'],
    'Big Tits': ['big boobs', 'bit tits', 'girl big tits', 'large tits', 'busty', 'big breasts', 'huge tits', 'huge boobs','big boobs (Natural)','busty natural','busty petite'],
    'Big Toys': ['big toy'],
    'Bikini': ['bikin','bikini babes'],
    'Blonde': ['blond', 'blond hair', 'blonde hair', 'blondes'],
    'Blow Bang': ['blowbang', 'blow bang','blow bangs','blowbangs'],
    'Blowjob': ['amateur blowjobs', 'bj', 'blow jobs', 'blow job', 'blowjob', 'blowjob (double)', 'blowjob (pov)', 'blowjob - double', 'blowjob - pov', 'blowjobs', 'sucking dick', 'cock sucking'],
    'Boots': ['boot'],
    'Boy-Boy-Boy-Girl': ['mmmf'],
    'Boy-Boy-Girl-Girl-Girl': ['fffmm'],
    'Boy-Boy-Girl-Girl': ['mmff'],
    'Boy-Boy-Girl': ['bbg', 'mmf', 'threesome bbg'],
    'Boy-Girl-Girl': ['2 girl bj', 'bgg', 'ffm', 'girl-girl-boy', 'threesome bgg', '2 Girls'],
    'Boy-Girl': ['boy girl', 'girl-boy', 'girl/boy'],
    'Braces': ['metal mouth'],
    'Bride' :  ['brides'],
    'Breast Bondage': ['best bound breasts'],
    'Brunette': ['brown hair', 'brunet', 'brunettes','brown hair (Female)'],
    'Bukkake': ['bukakke'],
    'Butt Plug': ['anal plug', 'buttplug'],
    'Camel Toe': ['camel toe pussy'],
    'Caucasian': ['while', 'white', 'white girl', 'white girls', 'caucasian actress', 'white actress'],
    'CBT': ['death defying cbt'],
    'Chastity Play': ['chastity'],
    'Cheerleaders' : ['cheer leader','cheer leaders','cheerleader','cheerleaders'],
    'Coeds': ['coed', 'college', 'university'],
    'Colored Hair': ['hair color', 'other hair color'],
    'Cop': ['police'],
    'Cosplay': ['costume', 'uniform'],
    'Couple': ['couples'],
    'Cowgirl (Position)': ['cow girl', 'cowgirl', 'cowgirl (pov)'],
    'Creampie': ['cream pie', 'creampie compilation', 'cum in pussy'],
    'Cuckold': ['brutal cuckolding', 'cuckolding','cuckolds'],
    'Cum In Mouth': ['cum-in-mouth'],
    'Cum On Face': ['cum in face'],
    'Cum Swallowing': ['cum swallow', 'cum swallowers', 'swallow cum', 'swallowing cum'],
    'Cum Swap': ['cum swapping', 'cumswap'],
    'Cumshot': ['cum shot', 'cum'],
    'Curly Hair': ['curly'],
    'Curvy': ['curvy woman', 'thick', 'voluptuous'],
    'Deep Throat': ['deepthroat', 'deepthroating', 'deepthoat'],
    'Dildo': ['dildo play'],
    'Dirty Talk': ['dirty talking'],
    'Doggystyle (Position)': ['doggy style', 'doggystyle', 'doggy'],
    'Domination' : ['dominance','dominant woman','domination','slave'],
    'Double Penetration (DP)': ['double penetration', 'double penetraton (dp)', 'dp'],
    'Double Anal Penetration (DAP)': ['double anal penetration', 'double anal penetraton (dap)', 'dap'],
    'Double Vaginal Penetration (DVP)': ['double vaginal penetration', 'double vaginal penetraton (dvp)', 'dvp'],
    'Double blowjob' : ['double blowjob', 'double blowjobs', 'double blowjobs (2 Mouths)','double blowjob (2 Mouths)','double bj'],
    'Ebony': ['african american', 'black', 'black girl', 'dark skin'],
    'Electro Play': ['electrical play', 'electrode punishments'],
    'European': ['euro', 'europe','eastern european'],
    'Face Fucking': ['face fuck', 'facefucking', 'facefuck', 'mouth fucking', 'mouthfucking'],
    'Face Sitting': ['facesitting', 'queening'],
    'Facial': ['cumshot facial', 'facial (multiple)', 'facial (pov)', 'facial - pov', 'facials', 'open mouth facial','facial cumshot'],
    'Fair Skin': ['pale', 'pale skin', 'whiteskin'],
    'Fake Tits': ['enhanced', 'enhanced tits', 'fake boobs', 'silicone tits'],
    'Feet': ['barefeet', 'foot'],
    'Fingering': ['finger fucking', 'fingering pussy'],
    'First Anal': ['first time anal'],
    'First Appearance': ['debut', 'first porn shoot', 'first time porn', 'model debut'],
    'First Interracial': ['first time ir'],
    'Fishnets': ['fishnet', 'fishnet stockings'],
    'Fisting': ['fisting\'s finest'],
    'Flat Chest': ['flat'],
    'Foot Job': ['footjob', 'footjobs'],
    'Gangbang': ['gangbangs'],
    'Gaping': ['gape', 'gaped ass', 'gaping playlist', 'gaping asshole'],
    'Girl-Girl Pissing': ['girl girl pissing', 'lesbian pissing'],
    'Girl-Girl': ['girl girl', 'girl on girl', 'girl-on-girl'],
    'Girlfriend Experience': ['gfe'],
    'Glamorous': ['glamour'],
    'Group Sex': ['group', 'groupe sex'],
    'Gym': ['gym selfie porn', 'in the gym'],
    'Hairy Pussy': ['bush', 'hairy', 'hairy bush'],
    'Hand Job': ['handjob', 'handjob (pov)', 'handjob - pov', 'handjobs', 'hanjob'],
    'Hardcore': ['hardcore sex'],
    'Heterosexual': ['straight', 'straight porn'],
    'High Heels': ['heels'],
    'Holidays': ['holidayparty', 'holiday'],
    'Hood': ['hooded'],
    'Hotel Room': ['hotel'],
    'Housewife': ['housewives'],
    'Indoors': ['indoor'],
    'Interracial': ['ir'],
    'Interview': ['interviews'],
    'Jerk Off Instructions (JOI)': ['jerk off instruction', 'joi', 'joi games'],
    'Landing Strip': ['landing strip pussy'],
    'Latex': ['latex darlings'],
    'Latina': ['latinas', 'latin','latina woman'],
    'Lesbian': ['lesbians'],
    'Lezdom': ['lesbian domination'],
    'Lingerie': ['lenceria'],
    'Maid': ['maid fetish','maids','french maid','french maids'],
    'Mask': ['masks'],
    'Massage': ['body massage', 'masseuse','masseur'],
    'Masturbation': ['masturbacion', 'masturbating'],
    'Medical Fetish': ['doctor', 'doctor/nurse', 'nurse', 'nurse play'],
    'Medium Tits': ['medium boobs'],
    'MILF & Mature': ['mature & milf'],
    'MILF': ['milfs'],
    'Mini Skirt': ['miniskirts'],
    'Missionary (Position)': ['missionary', 'missionary (pov)', 'missionary - pov'],
    'Model': ['modelo'],
    'Muscular': ['muscle'],
    'Natural Tits': ['natural boobs', 'real tits', 'natural breasts', 'real boobs', 'real breasts'],
    'Nerd': ['nerdy'],
    'Nude': ['completely naked', 'naked'],
    'Office Setting': ['office'],
    'Oil': ['babyoil', 'oiled', 'oil / lotion'],
    'Older/Younger': ['older / younger'],
    'One-On-One': ['1 on 1'],
    'Oral Sex': ['oral'],
    'Orgasms': ['amazing orgasms', 'orgasm'],
    'Orgy': ['four or more'],
    'Outdoor Sex': ['outdoors','outdoor','outdoor sex','outside fuck', 'outside'],
    'Paddle': ['paddling'],
    'Panties': ['braguitas'],
    'Pantyhose & Stockings': ['black stockings', 'nude stockings', 'nylons stockings', 'pantyhose', 'pantyhose / stockings', 'pantyhose footjobs', 'stocking', 'stockings'],
    'Petite': ['skinny'],
    'Pierced Nipples': ['pierced nipple'],
    'Piercing': ['piercings'],
    'Pile Driver': ['pile driving'],
    'Piss Play': ['pee', 'pissing'],
    'Pool': ['poolparty'],
    'Pornstar Experience': ['pse'],
    'Pornstar': ['pornstars', 'porn star'],
    'POV': ['femdom pov', 'p.o.v.'],
    'Public Sex': ['public'],
    'Pussy Eating': ['cunilingus', 'pussy lick', 'pussy licking', 'licking pussy', 'eating pussy', 'pussy-eating'],
    'Reality Porn': ['reality'],
    'Redhead': ['red head', 'red heads','red hair (female)','red hair'],
    'Reverse Cowgirl (Position)': ['cowgirl - pov', 'reverse cow girl', 'reverse cowgirl', 'reverse cowgirl (pov)', 'reverse cowgril', 'reeverse cowgirl'],
    'Rim Job': ['rimjob', 'rimming'],
    'Schoolgirl': ['school girl', 'schoolgirl','schoolgirls','school girls','schoolgirl outfit','schoolgirls outfit'],
    'Sci-Fi and Fantasy': ['sci fi'],
    'Self Sucking': ['self-sucking'],
    'Sex': ['sexo'],
    'Shaven Pussy': ['bald pussy', 'shaved', 'shaved pussy'],
    'Shoe Fetish': ['shoeplay', 'sneaker fetish'],
    'Sissification': ['sissy training course'],
    'Skirt': ['skirts'],
    'Small Ass': ['small booty', 'small butt'],
    'Small Tits': ['small boobs', 'tiny breasts', 'tiny tits', 'tiny boobs', 'small breasts', 'little boobs', 'little breasts', 'little tits'],
    'Solo': ['solo action', 'solo masturbation', 'solo sex'],
    'Spooning': ['spoon'],
    'Sports' : ['sports sra','sportswear','sport'],
    'Squirting': ['squirt', 'top squirting videos'],
    'Step Daughter': ['stepdaughter'],
    'Step Mom': ['stepmom'],
    'Step Sister': ['ste sister', 'step sis', 'step siter', 'step-sister', 'stepsis', 'stepsister'],
    'Strap-On': ['pov strapon', 'strap on'],
    'Striptease': ['strip tease'],
    'Swallowing': ['amateur swallow', 'swallow'],
    'Tan Lines': ['tanlines'],
    'Tan': ['tanned skin'],
    'Tattoo': ['tattoo girl', 'tattooed', 'tattoos', 'inked'],
    'Teacher': ['teacher','teachers'],
    'Tease and Denial': ['tease & denial'],
    'Teen': ['18+ teen', 'bad teens punished', 'teen porn', 'teen role', 'teens',"18-Year-Old",'18', '18 year', 'eighteen and...', 'eighteen','19', 'nineteen'],
    'Thong': ['thongs'],
    'Threesome': ['2 on 1', '2-on-1', '2on1', '3 way', '3some', 'threesomes', '3way'],
    'Throat Fucking': ['Throat Fuck'],
    'Tit Sucking': ['tit suck', 'tit sucking', 'titty sucking', 'tit-sucking'],
    'Titty Fuck': ['tit fuck', 'tit fucking', 'titty fucking', 'tittyfuck', 'tittyfuck (pov)', 'tittyfuck - pov', 'titfuck', 'titjob', 'titsjob', 'tit-fucking'],
    'Toys': ['sex toys', 'toy insertions'],
    'Transsexual': ['trans', 'transexual', 'ts'],
    'Tribbing': ['scissoring'],
    'Trimmed Pussy': ['trimmed', 'trimmed bush', 'groomed pussy'],
    'Twerking': ['tweking'],
    'Uncircumcised': ['uncut dicks'],
    'Uniform': ['uniforms'],
    'Valentine\'s Day': ['valentines day'],
    'Video Game': ['videogame'],
    'Whipping': ['whip'],
}

GenresSkip = [
    '18+ teens',
    '18+teens',
    '35 plus',
    '4k',
    "4k available",
    "adult time original",
    "american",
    "american man",
    "american men",
    '60p',
    'acworthy',
    'april showers',
    'april',
    'beaverday',
    'bonus',
    'daylight savings',
    'desert apocalypse',
    'destruction',
    'episode',
    'exclusive',
    'extra update',
    'faces of pain',
    'feel me',
    'get sprung',
    'gonzo',
    'grey',
    'hd videos',
    'heavymetal',
    'irreconcilable slut',
    'keiran',
    'little runaway',
    'mr. cummings',
    'photos',
    'public disgrace\'s best',
    'ryan mclane',
    'show less',
    'show more',
    'site member',
    'smart',
    'spring cleaning',
    'st patrick\'s day',
    'the pope',
    'tj cummings',
    'tony',
    'twistys hard',
    'tyler steele',
    'van styles',
    'workitout',
    'wow girls special',
    'yes, mistress',
    '25-34',
    '35 Plus' ,
    '4k Available',
    '90s Porn Video',
    'Action',
    'Adult',
    'Adult Time Original',
    'Adultery',
    'Adventure',
    'Airtight',
    'Alley',
    'American',
    'American Man',
    'Anal College',
    'Anal Doggy Style',
    'Anal Fingering',
    'Anal Fisting',
    'Anal Full Nelson',
    'Anal Gape',
    'Anal Gaping',
    'Anal Masturbation',
    'Anal Play',
    'Anal Queens',
    'Anal Reverse Cowgirl',
    'Anal Spooning',
    'Anal Toys',
    'Animation',
    'Appearance',
    'Arab',
    'Arabic',
    'Army Man',
    'Artist',
    'Ass Eating',
    'Ass Fetish',
    'Ass Jiggle',
    'Ass Masterpiece',
    'Ass Play',
    'Ass Smacking',
    'Ass Stacking',
    'Ass Tease',
    'Asshole',
    'Asshole Licking',
    'Assorted Additional Tags',
    'amazing orgasms',
    'Atp',
    'Australian',
    'Aventure',
    'Average',
    'Average Body',
    'Average Dick',
    'Average Height Woman',
    'Average Male Body',
    'Averagebody',
    'Avn Awards',
    'AVN Top 500',
    'Awards',
    'Ball Licking',
    'Ball Play',
    'Ball sucking',
    'Balls-Deep-Anal',
    'Bareback',
    'Barefoot',
    'Barn',
    'Bathtub',
    'BBW',
    'Bed',
    'Bedroom',
    'Belly Button',
    'Belly Button Piercings',
    'Belt',
    'Belts',
    'Bg Climax',
    'Bg Cunnilingus',
    'Bg Doggy Style',
    'Bg Fingering',
    'Bg Kissing',
    'Big',
    'Big Clit',
    'Big Dick Worship',
    'Big Legs',
    'Big Nipples',
    'Bimbo',
    'Biography',
    'Birthday',
    'Black Friday',
    'Black Hair',
    'Black Hair (female)',
    'Black Hair (Male)',
    'Black Male',
    'Black Man',
    'Black Men',
    'Black Woman',
    'Blackmail',
    'Blindfold',
    'Blond Hair (Male)',
    'Blouse',
    'Blue Collar',
    'Body Painting',
    'Bodyguard',
    'Bondage Collar',
    'Boob Flashing',
    'Boob Play',
    'Boots',
    'Booty Shorts',
    'Bored',
    'Boss',
    'Bottomless',
    'Bouncing Tits',
    'Boxed Sets',
    'Boy / Girl',
    'Boy-Boy-Girl-Girl-Girl',
    'Boyfriend',
    'Boyshorts',
    'Bra',
    'Bra and Panties',
    'Braces',
    'Braids',
    'Bratty Sis.com',
    'Breast Licking',
    'Breast Play',
    'Breast Sucking',
    'Bridge',
    'British',
    'Brown Eyes',
    'Brown Hair (Male)',
    'Business Man',
    'Business Woman',
    'Butt Flashing',
    'Butt Fucking',
    'Butt Plug',
    'Butthole',
    'Butthole Licking',
    'Camel Toe',
    'camel toe pussy',
    'Canadian',
    'Cap',
    'Carpet',
    'Casual Sex',
    'Caught',
    'Celebrity Sex Tapes',
    'CFNM',
    'Character',
    'Chef',
    'Choker',
    'Choking',
    'Chubby',
    'Cinematic - Story',
    'Classroom',
    'Cleaning',
    'Close Up',
    'Close Up Ass',
    'Close Up Pussy',
    'Coach',
    'Cock',
    'Cock Worship',
    'Coeds',
    'Collections',
    'Colored Stockings',
    'Comedy',
    'Comic',
    'Condom',
    'Corset',
    'Costume',
    'Couch',
    'Couple',
    'Couple Sex',
    'Couples',
    'Couples Fantasies',
    'Crazy Sex',
    'Creampie Eating',
    'Creampie Eating From Other',
    'Crime',
    'Criminal',
    'Crop Top',
    'Cum Drip',
    'Cum eating',
    'Cum On Stomach',
    'Cum Play',
    'Cum-Eating',
    'Cumming',
    'Cumonass',
    'Cumplay',
    'Cumshot Clean-Up',
    'Cumswapping',
    'Cunnilingus',
    'Curly hair',
    'Customer',
    'Cute',
    'Dark Hair',
    'Deep Fuck',
    'Denim Shorts',
    'Desk',
    'Dfxtra Exclusive',
    'Dick Play',
    'Dildo',
    'Directed by Women',
    'Dirty Talk',
    'Dirty Wives Club',
    'Documentary',
    'Doggy Pose',
    'Doggystyle - Lying',
    'Doggystyle - Pov',
    'Doggystyle - Standing',
    'Double Handed',
    'Drama',
    'Drame',
    'Dungeon',
    'Dungeons',
    'Dutch',
    'E Girls',
    'Earrings',
    'Ebony',
    'Enema',
    'Erect Nipples',
    'Erotic Vignette',
    'Erotica',
    'Ethnic',
    'Exclusives',
    'Eyeglasses',
    'Eyes - Blue',
    'Eyes - Brown',
    'Eyes - Green',
    'Eyes - Hazel',
    'Face Down Ass Up',
    'Face fuck',
    'Face Fucking',
    'Face Sitting',
    'Facesitting',
    'Fair Skin',
    'Fairy Tales',
    'Fake Boobs',
    'Fake Nails',
    'Fake Tits',
    'Family Roleplay',
    'Fan Submitted',
    'Fans',
    'Fantasy',
    'Feature',
    'Feet',
    'Female Doctor',
    'Female Squirting',
    'Femdom',
    'Fetish Food',
    'Fingering',
    'First Anal',
    'First Man/Woman',
    'First Time',
    'Fishnet',
    'Fishnets',
    'Fisting',
    'Flashing',
    'Flexible',
    'FM',
    'Fondling',
    'Food',
    'Foot Fetish',
    'Foot Job',
    'Footjob',
    'Foreign Accent',
    'Freckles',
    'Freeuse',
    'Fuck N Lick',
    'Full Nelson',
    'Full Time Jobs',
    'G-String',
    'Gagging',
    'Gags',
    'Game',
    'Garter Belt',
    'General',
    'Ghost Nipples',
    'Girl Orgasm',
    'Girl-Girl',
    'Girlfriend',
    'Gloves',
    'Golden Shower',
    'Goth Girls',
    'Gray Hair',
    'Green Eyes',
    'Hair Accessories',
    'Hair Pulling',
    'Hairless Genitals',
    'Hairless Labia',
    'Hairless Pussy',
    'Handcuffs',
    'Handy Man',
    'Hat',
    'Head Band',
    'Heterosexual',
    'High Definition Dvds',
    'History',
    'Horror',
    'Hot Pants',
    'Hotel Room',
    'Hotwife',
    'Husband',
    'Innie Pussy',
    'Innocent',
    'International',
    'Interracial',
    'Interracial - Black Men',
    'Interracial - Caucasian Girls',
    'Interview',
    'Inverted Nipples',
    'Italian Language',
    'J.O.E.',
    'Jacket',
    'Jean Shorts',
    'Jeans',
    'Jewelry',
    'Jockey',
    'Jockey Position',
    'Kinky',
    'Kissing',
    'La-Dolce-Vita',
    'Lace',
    'Landing Strip',
    'Language',
    'Large Labia',
    'Latino Man',
    'Lawyer',
    'Leather',
    'Leg Fetish',
    'Leggings',
    'Legs',
    'Legs Up Missionary',
    'Lesbian',
    'Licking Tits',
    'Lifeguard',
    'Light',
    'Light Skin',
    'Living Room',
    'Long',
    'Long - Straight',
    'Long Hair',
    'Mail-Order Bride',
    'Male Boss',
    'Male Plumber',
    'Male Prisoner',
    'Male Teacher',
    'Manicured',
    'Married',
    'Mask',
    'Massage',
    'Masseur',
    'Masseuse',
    'Masturbating',
    'Masturbation',
    'Masturbation During Sex',
    'Mature',
    'Mature (30+)',
    'Meat Curtains',
    'Medical Fetish',
    'Medium',
    'Medium Ass',
    'Medium Boobs',
    'Medium Hair',
    'Medium Height',
    'Medium Natural Tits',
    'Medium Skin',
    'Medium Tits',
    'Mediumass',
    'Mediumskin',
    'MILF',
    'MILF (30+)',
    'Military',
    'Military Man',
    'Mixed Ethnicity',
    'Moaning',
    'Modelesque',
    'Money Shot',
    'Mother',
    'Multiple Cum Clean-up',
    'Muscular',
    'Muscular Man',
    'Mystery',
    'Narrative',
    'Native',
    'Natural Light',
    'Niche',
    'Nipple Piercing',
    'Nipple Piercings',
    'Nipple Play',
    'No Bra',
    'No Condom',
    'No Piercings',
    'No Tattoos',
    'No Underwear',
    'Nose Piercing',
    'Nude',
    'Obedience',
    'Object Insertion',
    'Office Setting',
    'Older / Younger',
    'Older Men',
    'Older/Younger',
    'One on one',
    'One-On-One',
    'One-Piece',
    'Oral Fetish',
    'Oral Train',
    'Orgasm',
    'Orgasms',
    'Outie Pussy',
    'Outiepussy',
    'Pantyless',
    'Parents',
    'Park',
    'Parking Lot',
    'Passion',
    'Pawg',
    'Pearl Necklace',
    'Perky',
    'Pervert',
    'Petite',
    'Photographer',
    'Piercing',
    'Pigtails',
    'Pile Driver',
    'Piledriver',
    'Pilot',
    'Pilots',
    'Pinay',
    'Pink',
    'Pirates',
    'Platform',
    'Pleasure',
    'Plot Oriented',
    'Podcast',
    'Ponytail',
    'Popular with Women',
    'Principal',
    'Prison',
    'Prisoner',
    'Professional Production',
    'Prone Bone',
    'Public Nudity',
    'Puffy Nipples',
    'Punk Girl',
    'Pussy',
    'Pussy Clamps',
    'Pussy Creampie',
    'Pussy Eating',
    'Pussy Fingering',
    'Pussy Fucking',
    'Pussy Licking',
    'Pussy Lips',
    'Pussy Play',
    'Pussy Rubbing',
    'Pussy Tease',
    'Pussy To Mouth',
    'Reality',
    'Reality Porn',
    'Religion',
    'Reluctant',
    'Remaster',
    'Revenge',
    'Reverse Piledriver',
    'Riding',
    'Rim Job',
    'Rimming',
    'Rimming Her',
    'Rimming Him',
    'Robe',
    'Roleplay',
    'Romance',
    'Romantic',
    'Sandals',
    'Sci Fi And Fantasy',
    'Science Fiction',
    'Scissoring',
    'See-Through',
    'Series',
    'Settings',
    'Sex',
    'Sex Toy Play',
    'Sextape',
    'Share',
    'Shaved Head',
    'Shoes',
    'Short',
    'Short Dress',
    'Short Hair',
    'Short Hair & Pixie',
    'Short Hair (Male)',
    'Short Skirt',
    'Short Woman',
    'Shorts',
    'Shrimping',
    'Shy',
    'Side Cowgirl',
    'Side Fuck Blowjob',
    'Side Rider',
    'Skinny',
    'Skirt',
    'Skirts',
    'Slapping',
    'Slim',
    'Slip',
    'Slow Dance',
    'Slow Mo',
    'Small',
    'Small Ass',
    'Small Boobs',
    'Small Natural Tits',
    'Small Tits',
    'Smoking',
    'Sneakers',
    'Sneaky',
    'Soap',
    'Socks',
    'Sofa',
    'Softcore',
    'Solo',
    'Spanking',
    'Speculum',
    'Spit Bubbles',
    'Spit Roast',
    'Spit Stringers',
    'Spitting',
    'Split Going Forward',
    'Spooning Blowjob',
    'Spread Ass',
    'Spread Legs',
    'Squirting',
    'Stand And Carry',
    'Standing Cradle',
    'Standing Doggy Style',
    'Standing Doggystyle',
    'Standing Sex',
    'Star Showcase',
    'Stealing',
    'Step Brother',
    'Step Dad',
    'Step Mom',
    'Step Mother',
    'Step Siblings',
    'Step Son',
    'Stepdad',
    'Stewardess',
    'Stillettos',
    'Stockings',
    'Stockings (Black)',
    'Store',
    'Storyline',
    'Straight Hair',
    'Strap-On',
    'Streamer',
    'Studying',
    'Submission',
    'Submissive',
    'Sucking Fingers',
    'Sucking Tits',
    'Sultry',
    'Sunlit',
    'Super Woman',
    'Suspender Belt',
    'Sweat Pants',
    'Sweater',
    'Sweaty',
    'Swingers',
    'T-Shirt',
    'Table',
    'Taboo',
    'Tall',
    'Tan',
    'Tan Lines',
    'Tank Top',
    'Tanned Skin',
    'Tattoo',
    'Tattoos',
    'Tease',
    'Teddy',
    'Tenants',
    'Theater',
    'Thigh High Stockings',
    'Thong',
    'Girl-Girl Pissing',
    'Thriller',
    'Throat Fucking',
    'Tie',
    'Tiny Woman',
    'Toe Focus',
    'Toned',
    'Toys',
    'Travel Sex',
    'Tribbing',
    'Trimmed Pussy',
    'Trimmedpussy',
    'Tushy',
    'Tutoring',
    'Twerking',
    'Twins',
    'Twosome',
    'Twosome (Lesbian)',
    'Twosome (Straight)',
    'Uncircumcised',
    'United Kingdom',
    'Upskirt',
    'Vaginal',
    'Vaginal Penetration',
    'Vaginal Sex',
    'Vibrator',
    'Washing',
    'Water',
    'Water Play',
    'Weird',
    'Wet',
    'Wet Look',
    'White Man',
    'White Woman',
    'Wife',
    'Wild',
    'Wild Sex',
    'Woman (20-29)',
    'Woman 30-39',
    'Woman\'s Heels',
    'Work Fantasies',
    'X',
    'XRCO Awards',
    'Yoga',
    'Young (22-30)',
    'Young Woman (22-30)',
]

GenresPartialSkip = [
    '1080p',
    '5k',
    '60fps',
    'aprilfools',
    'chibbles',
    'folsom',
    'hd',
]
